### ISSUE TITLE
Can't Get MipoSaur to turn

### ISSUE THREAD

**Issue by HedgeHogTerror** [hongkongkiwi/MiPosaur-BLE-Protocol#2]
Hi there. I am tinkering with a Miposaur, I have gotten it to drive forward/backwards using the command 0x78, and the values 0x00-0x40. However when I try to write above that (corresponding to a turn) it does not appear to do anything. I have gotten other commands to work like changing the light color, and playing sounds, but also the turn by angle command 0x73, and 0x74 do not work. Not sure what the issue is. The characteristic handle should be the same for all these, correct?

**Comment by adamgreen** [comment]
I found the continuous drive command to be a bit confusing when I first started playing with the original MiP. Two things I would note:
- The continuous drive command (0x78) requires two data bytes and not just one byte. The first byte is the forward/backward velocity and the second byte indicates how quickly it should turn to the left/right while driving forward/backward.
- You need to keep sending the continuous drive command at regular intervals (~50 msec) to keep the bot driving smoothly.

I have [documentation here](https://github.com/adamgreen/MiP-Capi#mipcontinuousdrive) on how to use the mipContinuousDrive() in my C API for the MiP.

My implementation of that C API and how it fills in the two data bytes can be [seen here](https://github.com/adamgreen/MiP-Capi/blob/master/mipcapi/mip.c#L296).

**Comment by HedgeHogTerror** [comment]
Thanks for the response! I found out my main issue was that it was not in "driving mode". You must place the bot upright in its auto balancing mode for it to accept the turning commands. Oddly it can still accept just forward/backward when it is "sitting". Makes sense I suppose. 

Anyway, thanks again!
